/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi.view;

import br.com.pi.DAO.ControleFuncionários;
import br.com.pi.factory.ConnectionFactory;
import br.com.pi.model.Funcionários;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class FormFuncionários extends javax.swing.JFrame {
    
    Funcionários funcionarios = new Funcionários();
    ControleFuncionários controle = new ControleFuncionários();
    ConnectionFactory conexao = new ConnectionFactory();
    int flag = 0;

    
    public FormFuncionários() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereço = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JTextField();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabelcep = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelcelular = new javax.swing.JLabel();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelendereco = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelsenha = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelCadastrodefuncionários = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Funcionários");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(27, 512, 0, 0);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);
        jPanel2.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(350, 0, 50, 320);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 320, 710, 30);

        jTextFieldMunicipio.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMunicipio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldMunicipio.setEnabled(false);
        jPanel2.add(jTextFieldMunicipio);
        jTextFieldMunicipio.setBounds(490, 30, 200, 30);

        jTextFieldCPF.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCPF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCPF.setEnabled(false);
        jPanel2.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(140, 150, 200, 30);

        jTextFieldCelular.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCelular.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCelular.setEnabled(false);
        jPanel2.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(140, 270, 200, 30);

        jTextFieldNome.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldNome.setEnabled(false);
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(140, 30, 200, 30);

        jTextFieldEndereço.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEndereço.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldEndereço.setEnabled(false);
        jPanel2.add(jTextFieldEndereço);
        jTextFieldEndereço.setBounds(490, 150, 200, 30);

        jTextFieldCEP.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCEP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCEP.setEnabled(false);
        jPanel2.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(490, 210, 200, 30);

        jTextFieldPesquisa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(150, 340, 400, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldEmail.setEnabled(false);
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(140, 90, 200, 30);

        jComboBoxEstado.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxEstado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        jComboBoxEstado.setEnabled(false);
        jPanel2.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(490, 90, 200, 30);

        jLabelcep.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcep.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcep.setText("CEP:");
        jPanel2.add(jLabelcep);
        jLabelcep.setBounds(380, 210, 100, 30);

        jLabelCPF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF:");
        jPanel2.add(jLabelCPF);
        jLabelCPF.setBounds(20, 150, 100, 30);

        jLabelGenero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Gênero:");
        jPanel2.add(jLabelGenero);
        jLabelGenero.setBounds(20, 210, 100, 30);

        jLabelcelular.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcelular.setText("Celular:");
        jPanel2.add(jLabelcelular);
        jLabelcelular.setBounds(20, 270, 100, 30);

        jLabelMunicipio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMunicipio.setText("Município:");
        jPanel2.add(jLabelMunicipio);
        jLabelMunicipio.setBounds(380, 30, 100, 30);

        jLabelEstado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Estado:");
        jPanel2.add(jLabelEstado);
        jLabelEstado.setBounds(380, 90, 100, 30);

        jLabelendereco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelendereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelendereco.setText("Endereço:");
        jPanel2.add(jLabelendereco);
        jLabelendereco.setBounds(380, 150, 100, 30);

        jLabelNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome:");
        jPanel2.add(jLabelNome);
        jLabelNome.setBounds(20, 30, 100, 30);

        jLabelsenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelsenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsenha.setText("Senha:");
        jPanel2.add(jLabelsenha);
        jLabelsenha.setBounds(380, 270, 100, 30);

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(20, 90, 100, 30);

        jTextFieldSenha.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSenha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldSenha.setEnabled(false);
        jPanel2.add(jTextFieldSenha);
        jTextFieldSenha.setBounds(490, 270, 200, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(560, 340, 130, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(150, 380, 540, 240);

        jButtonSalvar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar);
        jButtonSalvar.setBounds(10, 430, 100, 30);

        jButtonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);
        jButtonCancelar.setBounds(10, 480, 100, 30);

        jButtonEditar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar);
        jButtonEditar.setBounds(10, 530, 100, 30);

        jButtonExcluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExcluir);
        jButtonExcluir.setBounds(10, 590, 100, 30);

        jButtonNovo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNovo);
        jButtonNovo.setBounds(10, 380, 100, 30);

        jComboBoxGenero.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxGenero.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBoxGenero.setEnabled(false);
        jPanel2.add(jComboBoxGenero);
        jComboBoxGenero.setBounds(140, 210, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 50, 710, 630);

        jLabelCadastrodefuncionários.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelCadastrodefuncionários.setText("Cadastro de Funcionários");
        getContentPane().add(jLabelCadastrodefuncionários);
        jLabelCadastrodefuncionários.setBounds(200, 10, 430, 40);

        setSize(new java.awt.Dimension(789, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jComboBoxGenero.setEnabled(true);
        jTextFieldMunicipio.setEnabled(true);
        jTextFieldEndereço.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jTextFieldSenha.setEnabled(true);        
        jTextFieldCPF.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldCelular.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(flag == 1){
        funcionarios.setNome(jTextFieldNome.getText());
        funcionarios.setEmail(jTextFieldEmail.getText());
        funcionarios.setGenero((String) jComboBoxGenero.getSelectedItem());
        funcionarios.setMunicipio(jTextFieldMunicipio.getText());
        funcionarios.setEndereco(jTextFieldEndereço.getText());
        funcionarios.setEstado((String) jComboBoxEstado.getSelectedItem());
        funcionarios.setSenha(jTextFieldSenha.getText());
        funcionarios.setCpf(jTextFieldCPF.getText());
        funcionarios.setCep(jTextFieldCEP.getText());
        funcionarios.setTel(jTextFieldCelular.getText());
        controle.Salvar(funcionarios);
        } else { 
            funcionarios.setNome(jTextFieldNome.getText());
            funcionarios.setEmail(jTextFieldEmail.getText());
            funcionarios.setGenero((String) jComboBoxGenero.getSelectedItem());
            funcionarios.setMunicipio(jTextFieldMunicipio.getText());
            funcionarios.setEndereco(jTextFieldEndereço.getText());
            funcionarios.setEstado((String) jComboBoxEstado.getSelectedItem());
            funcionarios.setSenha(jTextFieldSenha.getText());
            funcionarios.setCpf(jTextFieldCPF.getText());
            funcionarios.setCep(jTextFieldCEP.getText());
            funcionarios.setTel(jTextFieldCelular.getText());
            controle.Editar(funcionarios);
        }
        
        //limpar campos
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicipio.setText("");
        jComboBoxEstado.setEnabled(false);
        jTextFieldEndereço.setText("");
        jTextFieldSenha.setText("");        
        jTextFieldCPF.setText("");
        jTextFieldCEP.setText("");
        jTextFieldCelular.setText("");
        
        //Bloqueia os campos
        jTextFieldNome.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicipio.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        jTextFieldEndereço.setEnabled(false);
        jTextFieldSenha.setEnabled(false);        
        jTextFieldCPF.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldCelular.setEnabled(false);
        jButtonSalvar.setEnabled(false); 
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        funcionarios.setPesquisa(jTextFieldPesquisa.getText());
        Funcionários model = controle.buscaFuncionarios(funcionarios);
        
        jTextFieldNome.setText(model.getNome());
        jTextFieldEmail.setText(model.getEmail());
        jComboBoxGenero.setSelectedItem(model.getGenero());
        jTextFieldMunicipio.setText(model.getMunicipio());
        jTextFieldEndereço.setText(model.getEndereco());
        jComboBoxEstado.setSelectedItem(model.getEstado());
        jTextFieldSenha.setText(model.getSenha());
        jTextFieldCPF.setText(model.getCpf());
        jTextFieldCEP.setText(model.getCep());
        jTextFieldCelular.setText(model.getTel());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jComboBoxGenero.setEnabled(true);
        jTextFieldMunicipio.setEnabled(true);
        jTextFieldEndereço.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jTextFieldSenha.setEnabled(true);        
        jTextFieldCPF.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldCelular.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jComboBoxGenero.setEnabled(!true);
        jTextFieldMunicipio.setEnabled(!true);
        jTextFieldEndereço.setEnabled(!true);
        jComboBoxEstado.setEnabled(!true);
        jTextFieldSenha.setEnabled(!true);        
        jTextFieldCPF.setEnabled(!true);
        jTextFieldCEP.setEnabled(!true);
        jTextFieldCelular.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicipio.setText("");
        jTextFieldEndereço.setText("");
        jComboBoxEstado.setEnabled(false);
        jTextFieldSenha.setText("");        
        jTextFieldCPF.setText("");
        jTextFieldCEP.setText("");
        jTextFieldCelular.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta;
        resposta= JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja exluir?");
        if (resposta == JOptionPane.YES_OPTION){
            funcionarios.getId();
            controle.Excluir(funcionarios);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jTextFieldNome.setText("");
            jTextFieldEmail.setText("");
            jComboBoxGenero.setEnabled(false);
            jTextFieldMunicipio.setText("");
            jTextFieldEndereço.setText("");
            jComboBoxEstado.setEnabled(false);
            jTextFieldSenha.setText("");        
            jTextFieldCPF.setText("");
            jTextFieldCEP.setText("");
            jTextFieldCelular.setText("");
        } else{}
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastrodefuncionários;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelcelular;
    private javax.swing.JLabel jLabelcep;
    private javax.swing.JLabel jLabelendereco;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereço;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
