/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi.view;

import br.com.pi.DAO.ControleVeículos;
import br.com.pi.factory.ConnectionFactory;
import br.com.pi.model.Veículos;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class FormVeículos extends javax.swing.JFrame {
    Veículos veiculos = new Veículos();
    ControleVeículos controle = new ControleVeículos();
    ConnectionFactory conexao = new ConnectionFactory();
    int flag = 0;
    
    public FormVeículos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelcor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelMarca = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
        jButtoneditar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabelCadastrodeveiculos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Veículos");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jLabelPlaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca.setText("Placa:");
        jPanel1.add(jLabelPlaca);
        jLabelPlaca.setBounds(350, 80, 70, 60);

        jLabelNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Modelo do veículo:");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(10, 20, 140, 60);

        jLabelcor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelcor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcor.setText("Cor predominante:");
        jPanel1.add(jLabelcor);
        jLabelcor.setBounds(10, 140, 130, 58);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(310, 0, 20, 210);

        jLabelMarca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarca.setText("Marca:");
        jPanel1.add(jLabelMarca);
        jLabelMarca.setBounds(340, 10, 80, 80);

        jLabelAno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelAno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAno.setText("Ano do modelo:");
        jPanel1.add(jLabelAno);
        jLabelAno.setBounds(30, 80, 120, 58);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 210, 620, 10);

        jButtonExcluir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(20, 530, 110, 30);

        jButtonNovo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(20, 280, 110, 30);

        jButtonSalvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(20, 350, 110, 30);

        jButtoncancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtoncancelar.setText("Cancelar");
        jButtoncancelar.setEnabled(false);
        jButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoncancelar);
        jButtoncancelar.setBounds(20, 410, 110, 30);

        jButtoneditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtoneditar.setText("Editar");
        jButtoneditar.setEnabled(false);
        jButtoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoneditar);
        jButtoneditar.setBounds(20, 470, 110, 30);
        jPanel1.add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(150, 230, 310, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(480, 230, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 272, 460, 290);

        jTextFieldPlaca.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPlaca.setEnabled(false);
        jPanel1.add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(390, 100, 210, 30);

        jTextFieldNome.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNome.setEnabled(false);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(130, 40, 170, 30);

        jTextFieldAno.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAno.setEnabled(false);
        jPanel1.add(jTextFieldAno);
        jTextFieldAno.setBounds(130, 100, 170, 30);

        jTextFieldCor.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCor.setEnabled(false);
        jPanel1.add(jTextFieldCor);
        jTextFieldCor.setBounds(130, 160, 170, 30);

        jTextFieldMarca.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMarca.setEnabled(false);
        jPanel1.add(jTextFieldMarca);
        jTextFieldMarca.setBounds(390, 40, 210, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 620, 570);

        jLabelCadastrodeveiculos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelCadastrodeveiculos.setText("Cadastro de Veículos");
        getContentPane().add(jLabelCadastrodeveiculos);
        jLabelCadastrodeveiculos.setBounds(170, 0, 380, 60);

        setSize(new java.awt.Dimension(698, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jTextFieldCor.setEnabled(true);
        jTextFieldMarca.setEnabled(true);
        jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (flag == 1){
        veiculos.setNome(jTextFieldNome.getText());
        veiculos.setMarca(jTextFieldMarca.getText());
        veiculos.setPlaca(jTextFieldPlaca.getText());
        veiculos.setAno(jTextFieldAno.getText());
        veiculos.setCor(jTextFieldCor.getText());
        controle.Salvar(veiculos);
        } else{
            veiculos.setNome(jTextFieldNome.getText());
            veiculos.setMarca(jTextFieldMarca.getText());
            veiculos.setPlaca(jTextFieldPlaca.getText());
            veiculos.setAno(jTextFieldAno.getText());
            veiculos.setCor(jTextFieldCor.getText());
            controle.Editar(veiculos);
        }
       
        
        //limpar campos
        jTextFieldNome.setText("");
        jTextFieldMarca.setText("");
        jTextFieldPlaca.setText("");
        jTextFieldAno.setText("");
        jTextFieldCor.setText("");
        
        jTextFieldNome.setEnabled(false);
        jTextFieldMarca.setEnabled(false);
        jTextFieldPlaca.setEnabled(false);
        jTextFieldAno.setEnabled(false);
        jTextFieldCor.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        veiculos.setPesquisa(jTextFieldPesquisar.getText());
        Veículos model = controle.buscaVeiculos(veiculos);
        
        jTextFieldNome.setText(model.getNome());
        jTextFieldMarca.setText(model.getMarca());
        jTextFieldPlaca.setText(model.getPlaca());
        jTextFieldAno.setText(model.getAno());
        jTextFieldCor.setText(model.getCor());
       
        jButtoneditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditarActionPerformed
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jTextFieldAno.setEnabled(true);
        jTextFieldCor.setEnabled(true);
        jTextFieldMarca.setEnabled(true);
        jTextFieldPlaca.setEnabled(true);        
        jButtonSalvar.setEnabled(true);
        jButtoncancelar.setEnabled(!true);
        jButtonNovo.setEnabled(!true);
        jButtoneditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtoneditarActionPerformed

    private void jButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarActionPerformed
        jTextFieldNome.setEnabled(!true);
        jTextFieldAno.setEnabled(!true);
        jTextFieldCor.setEnabled(!true);
        jTextFieldMarca.setEnabled(!true);
        jTextFieldPlaca.setEnabled(!true);        
        jButtonSalvar.setEnabled(!true);
        jButtoncancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtoneditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldNome.setText("");
        jTextFieldAno.setText("");
        jTextFieldCor.setText("");
        jTextFieldMarca.setText("");
        jTextFieldPlaca.setText("");
    }//GEN-LAST:event_jButtoncancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta;
        resposta= JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja exluir?");
         if (resposta == JOptionPane.YES_OPTION){
            veiculos.getId();
            controle.Excluir(veiculos);
            jButtonExcluir.setEnabled(false);
            jButtoneditar.setEnabled(false);
            jTextFieldNome.setText("");
            jTextFieldMarca.setText("");
            jTextFieldPlaca.setText("");
            jTextFieldAno.setText("");
            jTextFieldCor.setText("");
        } else{}
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVeículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVeículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVeículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVeículos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVeículos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtoneditar;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCadastrodeveiculos;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelcor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
