/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi.view;

import br.com.pi.DAO.ControleMotoristas;
import br.com.pi.factory.ConnectionFactory;
import br.com.pi.model.Motoristas;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FormMotorista extends javax.swing.JFrame {
    Motoristas motoristas = new Motoristas();
    ControleMotoristas controle = new ControleMotoristas();
    ConnectionFactory conexao = new ConnectionFactory();
    int flag = 0;
    
    public FormMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroMotoristas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomecompleto = new javax.swing.JLabel();
        jTextFieldMunicípio = new javax.swing.JTextField();
        jLabelEndereço = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldNomecompleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEndereço = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSalvar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMotoristas = new javax.swing.JTable();
        jTextPesquisar = new javax.swing.JTextField();
        jButtonNovo1 = new javax.swing.JButton();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabelCadastrodeMotoristas = new javax.swing.JLabel();

        jLabelCadastroMotoristas.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCadastroMotoristas.setText("Cadastro de Motoristas");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Motoristas");
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));
        jPanel2.setLayout(null);

        jLabelNomecompleto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelNomecompleto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomecompleto.setText("Nome completo:");
        jPanel2.add(jLabelNomecompleto);
        jLabelNomecompleto.setBounds(10, 20, 100, 30);

        jTextFieldMunicípio.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMunicípio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldMunicípio.setToolTipText("Digite seu Municipio");
        jTextFieldMunicípio.setEnabled(false);
        jPanel2.add(jTextFieldMunicípio);
        jTextFieldMunicípio.setBounds(450, 20, 240, 30);

        jLabelEndereço.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelEndereço.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereço.setText("Endereço:");
        jLabelEndereço.setToolTipText("Digite seu Endereço");
        jPanel2.add(jLabelEndereço);
        jLabelEndereço.setBounds(380, 70, 70, 30);

        jTextFieldSenha.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSenha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldSenha.setToolTipText("Digite sua Senha");
        jTextFieldSenha.setEnabled(false);
        jTextFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldSenha);
        jTextFieldSenha.setBounds(450, 220, 240, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(360, 0, 10, 270);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 270, 700, 10);

        jLabelCPF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF:");
        jPanel2.add(jLabelCPF);
        jLabelCPF.setBounds(80, 70, 60, 30);

        jTextFieldNomecompleto.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNomecompleto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldNomecompleto.setToolTipText("Digite seu Nome");
        jTextFieldNomecompleto.setEnabled(false);
        jPanel2.add(jTextFieldNomecompleto);
        jTextFieldNomecompleto.setBounds(120, 20, 220, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 120, 50, 30);

        jTextFieldCPF.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCPF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCPF.setToolTipText("Digite seu CPF");
        jTextFieldCPF.setEnabled(false);
        jPanel2.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(120, 70, 220, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Município:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(380, 20, 70, 30);

        jTextFieldCelular.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCelular.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCelular.setToolTipText("Digite seu Celular");
        jTextFieldCelular.setEnabled(false);
        jPanel2.add(jTextFieldCelular);
        jTextFieldCelular.setBounds(120, 220, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 120, 50, 20);

        jTextFieldEndereço.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEndereço.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldEndereço.setToolTipText("Digite seu endereço");
        jTextFieldEndereço.setEnabled(false);
        jPanel2.add(jTextFieldEndereço);
        jTextFieldEndereço.setBounds(450, 70, 240, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEP:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(410, 170, 34, 30);

        jTextFieldCEP.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCEP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldCEP.setToolTipText("Digite seu CEP");
        jTextFieldCEP.setEnabled(false);
        jPanel2.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(450, 170, 240, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextFieldEmail.setToolTipText("Digite seu Email");
        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 120, 220, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(400, 210, 50, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gênero:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 170, 60, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Celular:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 220, 60, 30);

        jButtonExcluir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExcluir);
        jButtonExcluir.setBounds(10, 570, 120, 30);

        jButtonEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar);
        jButtonEditar.setBounds(10, 510, 120, 30);

        jButtonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);
        jButtonCancelar.setBounds(10, 450, 120, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(570, 280, 130, 30);

        jButtonSalvar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonSalvar1.setText("Salvar");
        jButtonSalvar1.setEnabled(false);
        jButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar1);
        jButtonSalvar1.setBounds(10, 390, 120, 30);

        jTableMotoristas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableMotoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMotoristas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 320, 560, 280);
        jPanel2.add(jTextPesquisar);
        jTextPesquisar.setBounds(140, 280, 420, 30);

        jButtonNovo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNovo1.setText("Novo");
        jButtonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNovo1);
        jButtonNovo1.setBounds(10, 320, 120, 30);

        jComboBoxGenero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBoxGenero.setEnabled(false);
        jPanel2.add(jComboBoxGenero);
        jComboBoxGenero.setBounds(120, 170, 220, 23);

        jComboBoxEstado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        jComboBoxEstado.setEnabled(false);
        jPanel2.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(450, 120, 240, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 60, 710, 620);

        jLabelCadastrodeMotoristas.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabelCadastrodeMotoristas.setText("Cadastro de Motoristas");
        getContentPane().add(jLabelCadastrodeMotoristas);
        jLabelCadastrodeMotoristas.setBounds(260, 10, 300, 50);

        setSize(new java.awt.Dimension(787, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvar1ActionPerformed
        if(flag == 1){
        motoristas.setNome(jTextFieldNomecompleto.getText());
        motoristas.setEmail(jTextFieldEmail.getText());
        motoristas.setGenero((String) jComboBoxGenero.getSelectedItem());
        motoristas.setMunicipio(jTextFieldMunicípio.getText());
        motoristas.setEndereco(jTextFieldEndereço.getText());
        motoristas.setEstado( (String) jComboBoxEstado.getSelectedItem());
        motoristas.setSenha(jTextFieldSenha.getText());
        motoristas.setCpf(jTextFieldCPF.getText());
        motoristas.setCep(jTextFieldCEP.getText());
        motoristas.setTel(jTextFieldCelular.getText());
        controle.Salvar(motoristas);
        } else{
            motoristas.setNome(jTextFieldNomecompleto.getText());
        motoristas.setEmail(jTextFieldEmail.getText());
        motoristas.setGenero((String) jComboBoxGenero.getSelectedItem());
        motoristas.setMunicipio(jTextFieldMunicípio.getText());
        motoristas.setEndereco(jTextFieldEndereço.getText());
        motoristas.setEstado( (String) jComboBoxEstado.getSelectedItem());
        motoristas.setSenha(jTextFieldSenha.getText());
        motoristas.setCpf(jTextFieldCPF.getText());
        motoristas.setCep(jTextFieldCEP.getText());
        motoristas.setTel(jTextFieldCelular.getText());
        controle.Editar(motoristas);
        jButtonCancelar.setEnabled(false);
        }
        
        //limpar campos
        jTextFieldNomecompleto.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicípio.setText("");
        jTextFieldEndereço.setText("");
        jComboBoxEstado.setEnabled(false);
        jTextFieldSenha.setText("");        
        jTextFieldCPF.setText("");
        jTextFieldCEP.setText("");
        jTextFieldCelular.setText("");
        
        //Bloqueia os campos
        jTextFieldNomecompleto.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicípio.setEnabled(false);
        jTextFieldEndereço.setEnabled(false);
        jComboBoxEstado.setEnabled(false);
        jTextFieldSenha.setEnabled(false);        
        jTextFieldCPF.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldCelular.setEnabled(false);
        jButtonSalvar1.setEnabled(false); 
        
       
    }//GEN-LAST:event_jButtonSalvar1ActionPerformed

    private void jButtonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo1ActionPerformed
        flag = 1;
        jTextFieldNomecompleto.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jComboBoxGenero.setEnabled(true);
        jTextFieldMunicípio.setEnabled(true);
        jTextFieldEndereço.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jTextFieldSenha.setEnabled(true);        
        jTextFieldCPF.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldCelular.setEnabled(true);
        jButtonSalvar1.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovo1ActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        motoristas.setPesquisa(jTextPesquisar.getText());
        Motoristas model = controle.buscaMotoristas(motoristas);
        
        jTextFieldNomecompleto.setText(model.getNome());
        jTextFieldEmail.setText(model.getEmail());
        jComboBoxGenero.setSelectedItem(model.getGenero());
        jTextFieldMunicípio.setText(model.getMunicipio());
        jTextFieldEndereço.setText(model.getEndereco());
        jComboBoxEstado.setSelectedItem(model.getEstado());
        jTextFieldSenha.setText(model.getSenha());
        jTextFieldCPF.setText(model.getCpf());
        jTextFieldCEP.setText(model.getCep());
        jTextFieldCelular.setText(model.getTel());
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
         jTextFieldNomecompleto.setEnabled(!true);
        jTextFieldEmail.setEnabled(!true);
        jComboBoxGenero.setEnabled(!true);
        jTextFieldMunicípio.setEnabled(!true);
        jTextFieldEndereço.setEnabled(!true);
        jComboBoxEstado.setEnabled(!true);
        jTextFieldSenha.setEnabled(!true);        
        jTextFieldCPF.setEnabled(!true);
        jTextFieldCEP.setEnabled(!true);
        jTextFieldCelular.setEnabled(!true);
        jButtonSalvar1.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo1.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldNomecompleto.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGenero.setEnabled(false);
        jTextFieldMunicípio.setText("");
        jTextFieldEndereço.setText("");
        jComboBoxEstado.setEnabled(false);
        jTextFieldSenha.setText("");        
        jTextFieldCPF.setText("");
        jTextFieldCEP.setText("");
        jTextFieldCelular.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomecompleto.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jComboBoxGenero.setEnabled(true);
        jTextFieldMunicípio.setEnabled(true);
        jTextFieldEndereço.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jTextFieldSenha.setEnabled(true);        
        jTextFieldCPF.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldCelular.setEnabled(true);
        jButtonSalvar1.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo1.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta;
        resposta= JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja exluir?");
        if (resposta == JOptionPane.YES_OPTION){
            motoristas.getId();
            controle.Excluir(motoristas);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jTextFieldNomecompleto.setText("");
            jTextFieldEmail.setText("");
            jComboBoxGenero.setEnabled(false);
            jTextFieldMunicípio.setText("");
            jTextFieldEndereço.setText("");
            jComboBoxEstado.setEnabled(false);
            jTextFieldSenha.setText("");        
            jTextFieldCPF.setText("");
            jTextFieldCEP.setText("");
            jTextFieldCelular.setText("");
        } else{}
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo1;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar1;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastroMotoristas;
    private javax.swing.JLabel jLabelCadastrodeMotoristas;
    private javax.swing.JLabel jLabelEndereço;
    private javax.swing.JLabel jLabelNomecompleto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableMotoristas;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereço;
    private javax.swing.JTextField jTextFieldMunicípio;
    private javax.swing.JTextField jTextFieldNomecompleto;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextPesquisar;
    // End of variables declaration//GEN-END:variables
}
