/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlanoDeFundo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsuário = new javax.swing.JTextField();
        jLabelUsuário = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelIconeIACIT = new javax.swing.JLabel();
        jLabelTextoExplicativo = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jButtonEsqueciasenha = new javax.swing.JButton();

        jLabelPlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/imagens/fundo azul.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jornada de trabalho de motoristas");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);
        jPanel1.add(jTextFieldUsuário);
        jTextFieldUsuário.setBounds(20, 130, 270, 30);

        jLabelUsuário.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUsuário.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuário.setText("Usuário:");
        jPanel1.add(jLabelUsuário);
        jLabelUsuário.setBounds(20, 100, 90, 30);

        jLabelSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(20, 180, 100, 20);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(20, 200, 270, 30);

        jLabelIconeIACIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/imagens/iacit.png"))); // NOI18N
        jPanel1.add(jLabelIconeIACIT);
        jLabelIconeIACIT.setBounds(320, 80, 180, 190);

        jLabelTextoExplicativo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTextoExplicativo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoExplicativo.setText("Controle de jornada de trabalho de motoristas");
        jPanel1.add(jLabelTextoExplicativo);
        jLabelTextoExplicativo.setBounds(20, 20, 490, 60);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar);
        jButtonEntrar.setBounds(30, 240, 63, 23);

        jButtonEsqueciasenha.setText("Esqueci a senha");
        jPanel1.add(jButtonEsqueciasenha);
        jButtonEsqueciasenha.setBounds(110, 240, 150, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 290);

        setSize(new java.awt.Dimension(565, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        if(jTextFieldUsuário.getText().equals("admin")&&jPasswordFieldSenha.getText().equals("1234")){
        TelaPrincipalFuncionário telafuncionario = new TelaPrincipalFuncionário();
        telafuncionario.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Senha ou Usuário Inválidos.");
        }
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonEsqueciasenha;
    private javax.swing.JLabel jLabelIconeIACIT;
    private javax.swing.JLabel jLabelPlanoDeFundo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTextoExplicativo;
    private javax.swing.JLabel jLabelUsuário;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuário;
    // End of variables declaration//GEN-END:variables
}
