/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pi.view;

import br.com.pi.factory.ConnectionFactory;

/**
 *
 * @author Dell
 */
public class TelaPrincipalFuncionário extends javax.swing.JFrame {
    
    ConnectionFactory conexao = new ConnectionFactory();
    
    
    /**
     * Creates new form TelaPrincipalFuncionário
     */
    public TelaPrincipalFuncionário() {
        initComponents();
        conexao.conexao(); //Após iniciar o sistema ele conecta ao Banco de dados
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlanoDeFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMotoristas = new javax.swing.JMenuItem();
        jMenuItemVeículos = new javax.swing.JMenuItem();
        jMenuItemFuncionários = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRelatório = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelPlanoDeFundo.setBackground(new java.awt.Color(102, 255, 102));
        jLabelPlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pi/imagens/fundo azul.jpg"))); // NOI18N
        jLabelPlanoDeFundo.setMaximumSize(getMaximumSize());
        getContentPane().add(jLabelPlanoDeFundo);
        jLabelPlanoDeFundo.setBounds(0, 0, 880, 450);

        jMenu1.setText("Cadastro");

        jMenuItemMotoristas.setText("Motoristas");
        jMenuItemMotoristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotoristasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMotoristas);

        jMenuItemVeículos.setText("Veículos");
        jMenuItemVeículos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeículosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemVeículos);

        jMenuItemFuncionários.setText("Funcionários");
        jMenuItemFuncionários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionáriosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFuncionários);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jMenuItemRelatório.setText("Relatório");
        jMenu2.add(jMenuItemRelatório);

        jMenuBar1.add(jMenu2);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(897, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMotoristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotoristasActionPerformed
        FormMotorista tela = new FormMotorista();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemMotoristasActionPerformed

    private void jMenuItemFuncionáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionáriosActionPerformed
        FormFuncionários funcionarios = new FormFuncionários();
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionáriosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conexao.desconecta(); //Desconecta do banco ao sair do sistema
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemVeículosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeículosActionPerformed
        FormVeículos tela1 = new FormVeículos();
        tela1.setVisible(true);
    }//GEN-LAST:event_jMenuItemVeículosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPlanoDeFundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemFuncionários;
    private javax.swing.JMenuItem jMenuItemMotoristas;
    private javax.swing.JMenuItem jMenuItemRelatório;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVeículos;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
